version = 0.1

[default.deploy.parameters]
stack_name = "lestes-tech-backend"
resolve_s3 = true
s3_prefix = "lestes-tech-backend"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\" S3BucketName=\"lestes-tech-media-store\" DynamoDBTableName=\"bloggs\""
image_repositories = []
